message(STATUS "")
message(STATUS "  CMake build type ................ : ${CMAKE_BUILD_TYPE}")
message(STATUS "  Build shared libs  .............. : ${BUILD_SHARED_LIBS}")
message(STATUS "  Build static libs  .............. : ${BUILD_STATIC_LIBS}")
message(STATUS "  Build example  .................. : ${BUILD_EXAMPLE}")
message(STATUS "  Build test ...................... : ${BUILD_TEST}")
message(STATUS "  Build c++ standard .............. : ${CMAKE_CXX_STANDARD}")
message(STATUS "  Build with boost::filesystem .... : ${USE_BOOST_FILESYSTEM}")
message(STATUS "")
message(STATUS " Dependencies:")
message(STATUS "  Boost version.................... : ${Boost_VERSION}")
message(STATUS "  Boost root....................... : ${Boost_DIR}")
message(STATUS "")
message(STATUS " Directories:")
message(STATUS "  CMAKE_PREFIX_PATH................ : ${CMAKE_PREFIX_PATH}")
message(STATUS "  INCLUDE_DIRECTORIES.............. : ${INCLUDE_DIRECTORIES}")
message(STATUS "  CMAKE_ARCHIVE_OUTPUT_DIRECTORY... : ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message(STATUS "  CMAKE_LIBRARY_OUTPUT_DIRECTORY... : ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message(STATUS "  CMAKE_RUNTIME_OUTPUT_DIRECTORY... : ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message(STATUS "")
